#!/bin/bash
#Update the package manager
#Yum in this case as it is ran on Amazon Linux
sudo yum update -y

#Install R
#sudo yum install -y R #OLD VERSION
sudo amazon-linux-extras install R3.4 -y

#Install RStudio-Server
#https://www.rstudio.com/products/rstudio/download-server/
wget https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.2.5019-x86_64.rpm
sudo yum -y install rstudio-server-rhel-1.2.5019-x86_64.rpm

#add user(s)
sudo useradd username
echo username:password | sudo chpasswd
